name = "backend"
main = "src/index.ts"
compatibility_date = "2024-08-11"


 [vars]
    DATABASE_URL=""


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
    binding = "BLOG_IMAGES"
    bucket_name = "my-blog-images"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"